### ISSUE TITLE
Error: Could not open file

### ISSUE THREAD

**Issue by fligi7** [blacktop/docker-yara#2]
Not sure what is going on, but I can't seem to get it to run using the documented command structure. 

Target file is located at /home/user/inventory.csv.
Yara rules directory is located at /home/user/rules/. 

`# docker run --rm -v /home/user/:/user -v /home/user/rules/:/rules blacktop/yara /rules/malware/RAT_Adzok.yar /user/inventory.csv`
could not open file

I'm sure it's something simple that I'm missing here.

**Comment by blacktop** [comment]
I'm thinking this line might be the issue https://github.com/blacktop/docker-yara/blob/master/3.5/Dockerfile#L50

I am downgrading to `nobody` which might not have perms to see your files as I see you are running as `root`?

**Comment by blacktop** [comment]
you could try `docker run --rm -v /home/user/:/user -v /home/user/rules/:/rules --entrypoint=sh blacktop/yara` and poke around inside the container to get a better idea of why it isnt working too

**Comment by fligi7** [comment]
I'm running as root, but shouldn't make a diff. I can run it as unpriv user as well. The file I'm trying to scan and my rules dir both have world read permissions for anyone (r--r--r--), so should work for either.

**Comment by blacktop** [comment]
can you run from inside the container?

**Comment by littlepwnie** [comment]
I have an issue, too. I provide the path to the rules file and the directory of the malware samples, but i cant understand what should i change in the last command.

docker run --rm -v ~/Documents/blah/blah/rules.yara:/rules:ro \
                  -v ~/samples:/malware:ro \
                  blacktop/yara /rules/RULES_FILE FILE

**Comment by blacktop** [comment]
are you getting the could not open file error?

**Comment by littlepwnie** [comment]
[image: Ενσωματωμένη εικόνα 1]
im probably syntaxing the command wrong somehow, but i dont know how... i
havent been using dockers so far. thanks

2017-10-15 19:54 GMT+03:00 blacktop <notifications@github.com>:
